### ISSUE TITLE
pip installation fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by duboism** [ismrmrd/ismrmrd-python#13]
The installation procedure tries to use `pyxb` before checking if it is installed:

```
$ pip install ismrmrd
Downloading/unpacking ismrmrd
Downloading ismrmrd-1.2.3.tar.bz2
Running setup.py (path:/tmp/pip_build_root/ismrmrd/setup.py) egg_info for package ismrmrd
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_root/ismrmrd/setup.py", line 6, in <module>
    import pyxb.binding.generate
ImportError: No module named pyxb.binding.generate
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 17, in <module>
File "/tmp/pip_build_root/ismrmrd/setup.py", line 6, in <module>
import pyxb.binding.generate
ImportError: No module named pyxb.binding.generate
```

After installing it manually (`$ sudo pip install pyxb`) the installation can proceed a bit further but then fails:

```
Running setup.py install for ismrmrd
ERROR:pyxb.utils.utility:open /tmp/pip_build_root/ismrmrd/schema/ismrmrd.xsd
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pyxb/utils/utility.py", line 740, in DataFromURI
    stream = open(uri, 'rb')
IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/ismrmrd/schema/ismrmrd.xsd'
error: [Errno 2] No such file or directory: '/tmp/pip_build_root/ismrmrd/schema/ismrmrd.xsd'
Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/ismrmrd/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-vSlIrP-record/install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_py
ERROR:pyxb.utils.utility:open /tmp/pip_build_root/ismrmrd/schema/ismrmrd.xsd
Traceback (most recent call last):
 File "/usr/local/lib/python2.7/dist-packages/pyxb/utils/utility.py", line 740, in DataFromURI
stream = open(uri, 'rb')
IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/ismrmrd/schema/ismrmrd.xsd'
error: [Errno 2] No such file or directory: '/tmp/pip_build_root/ismrmrd/schema/ismrmrd.xsd'
```

**Comment by hansenms** [comment]
Could you just try and start from a clean clone after installing pyxb, may have been some leftover stuff from previous build. In my 14.04 setup I install:

    pip install Cython
    pip install numpy pyxb h5py psutil Twisted lxml matplotlib  

Not all relevant for ismrmrd. Could you also give me the full version of your Ubuntu release.

**Comment by duboism** [comment]
I started from scratch (after rebooting the computer) and got the same error. 
I use an up-to-date Ubuntu 14.04.4 LTS.

Is `Twisted` needed? It's the only package that I haven't installed (but I have no idea of that can be related to the build error).

**Comment by hansenms** [comment]
Don't install ismrmrd from NeuroDebian. Use the source code repo. The Debian packages are old.

**Comment by hansenms** [comment]
I have just tried a blank Ubuntu 14.04.4 LTS installation in a Docker container. The Docker file I used was:

```
FROM ubuntu:14.04

RUN apt-get update --quiet && \
    apt-get install --no-install-recommends --no-install-suggests --yes  \
    wget build-essential emacs python-pip libhdf5-serial-dev cmake git-core \
    python-dev

#Python stuff
RUN pip install numpy
RUN pip install pyxb
RUN pip install h5py


#ISMRMRD PYTHON API
RUN mkdir -p /opt/code

RUN cd /opt/code && \
    git clone https://github.com/ismrmrd/ismrmrd-python.git &&  \
    cd ismrmrd-python && \
    sudo python setup.py install

#ISMRMRD PYTHON TOOLS
RUN cd /opt/code && \
    git clone https://github.com/ismrmrd/ismrmrd-python-tools.git &&  \
    cd ismrmrd-python-tools && \
    sudo python setup.py install
```

After building the image and starting the container, I am able to enter and use ismrmrd:

```
root@ccda3efdcd16:/# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ismrmrd
>>> import ismrmrdtools
>>> dir(ismrmrd) 
['ACQ_COMPRESSION1', 'ACQ_COMPRESSION2', 'ACQ_COMPRESSION3', 'ACQ_COMPRESSION4', 'ACQ_FIRST_IN_AVERAGE', 'ACQ_FIRST_IN_CONTRAST', 'ACQ_FIRST_IN_ENCODE_STEP1', 'ACQ_FIRST_IN_ENCODE_STEP2', 'ACQ_FIRST_IN_PHASE', 'ACQ_FIRST_IN_REPETITION', 'ACQ_FIRST_IN_SEGMENT', 'ACQ_FIRST_IN_SET', 'ACQ_FIRST_IN_SLICE', 'ACQ_IS_DUMMYSCAN_DATA', 'ACQ_IS_HPFEEDBACK_DATA', 'ACQ_IS_NAVIGATION_DATA', 'ACQ_IS_NOISE_MEASUREMENT', 'ACQ_IS_PARALLEL_CALIBRATION', 'ACQ_IS_PARALLEL_CALIBRATION_AND_IMAGING', 'ACQ_IS_PHASECORR_DATA', 'ACQ_IS_REVERSE', 'ACQ_IS_RTFEEDBACK_DATA', 'ACQ_IS_SURFACECOILCORRECTIONSCAN_DATA', 'ACQ_LAST_IN_AVERAGE', 'ACQ_LAST_IN_CONTRAST', 'ACQ_LAST_IN_ENCODE_STEP1', 'ACQ_LAST_IN_ENCODE_STEP2', 'ACQ_LAST_IN_MEASUREMENT', 'ACQ_LAST_IN_PHASE', 'ACQ_LAST_IN_REPETITION', 'ACQ_LAST_IN_SEGMENT', 'ACQ_LAST_IN_SET', 'ACQ_LAST_IN_SLICE', 'ACQ_USER1', 'ACQ_USER2', 'ACQ_USER3', 'ACQ_USER4', 'ACQ_USER5', 'ACQ_USER6', 'ACQ_USER7', 'ACQ_USER8', 'Acquisition', 'AcquisitionHeader', 'CHANNEL_MASKS', 'DATATYPE_CXDOUBLE', 'DATATYPE_CXFLOAT', 'DATATYPE_DOUBLE', 'DATATYPE_FLOAT', 'DATATYPE_INT', 'DATATYPE_SHORT', 'DATATYPE_UINT', 'DATATYPE_USHORT', 'DIRECTION_LENGTH', 'Dataset', 'EncodingCounters', 'IMAGE_IS_NAVIGATION_DATA', 'IMAGE_USER1', 'IMAGE_USER2', 'IMAGE_USER3', 'IMAGE_USER4', 'IMAGE_USER5', 'IMAGE_USER6', 'IMAGE_USER7', 'IMAGE_USER8', 'IMTYPE_COMPLEX', 'IMTYPE_IMAG', 'IMTYPE_MAGNITUDE', 'IMTYPE_PHASE', 'IMTYPE_REAL', 'Image', 'ImageHeader', 'Meta', 'NDARRAY_MAXDIM', 'PHYS_STAMPS', 'POSITION_LENGTH', 'USER_FLOATS', 'USER_INTS', '__all__', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', 'acquisition', 'constants', 'copy', 'ctypes', 'get_image_dtype', 'hdf5', 'image', 'meta', 'np', 'xsd']
```

The Ubuntu version:

```
root@ccda3efdcd16:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
```

So I am unable to reproduce your problem. Maybe you can use my exact command line instructions from the Docker file and any differences may be the explanation.

**Comment by hansenms** [comment]
@duboism did you have a chance to look at this?

**Comment by duboism** [comment]
@hansenms Sorry for the delay. I will try to look at this by the end of the week.

**Comment by frankong** [comment]
pip install also failed for me on Ubuntu 14.04, and on macOS 10.13, with similar error message as @duboism.

Installed from source with python setup.py works for me. It seems like the pypi package is not updated. Would one of the maintainers (@inati, @hansenms, @naegelejd) consider updating the pypi package?
