### ISSUE TITLE
ERROR: Could not build wheels for ismrmrd which use PEP 517 and cannot be installed directly :: windows 10

### ISSUE THREAD

**Issue by Pedro-Filipe** [ismrmrd/ismrmrd-python#40]
Hi,

I get the error below when trying to install in windows 10 with `pip install .`

Any suggestions?

Windows 10
miniconda python 3.9

```
Building wheels for collected packages: ismrmrd
  Building wheel for ismrmrd (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\adminUser\miniconda3\envs\fire\python.exe' 'C:\Users\adminUser\miniconda3\envs\fire\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' build_wheel 'C:\Users\ADMINU~1\AppData\Local\Temp\tmpofzgn431'
       cwd: C:\Users\adminUser\AppData\Local\Temp\pip-req-build-b_2k0b92
  Complete output (37 lines):
  running bdist_wheel
  running build
  running build_py
  Parsing schema ismrmrd.xsd
  Compiling schema ismrmrd.xsd
  Builder: 30 main and 1 inner classes
  Analyzer input: 30 main and 1 inner classes
  Analyzer output: 30 main and 0 inner classes
  Traceback (most recent call last):
    File "C:\Users\adminUser\miniconda3\envs\fire\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\adminUser\miniconda3\envs\fire\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\xsdata\__main__.py", line 15, in <module>
      main()
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\xsdata\__main__.py", line 8, in main
      cli()
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\click\core.py", line 1137, in __call__
      return self.main(*args, **kwargs)
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\click\core.py", line 1062, in main
      rv = self.invoke(ctx)
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\click\core.py", line 1668, in invoke
      return _process_result(sub_ctx.command.invoke(sub_ctx))
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\click\core.py", line 1404, in invoke
      return ctx.invoke(self.callback, **ctx.params)
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\click\core.py", line 763, in invoke
      return __callback(*args, **kwargs)
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\xsdata\cli.py", line 191, in generate
      transformer.process(list(uris))
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\xsdata\codegen\transformer.py", line 103, in process
      self.process_classes()
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\xsdata\codegen\transformer.py", line 180, in process_classes
      writer = CodeWriter.from_config(self.config)
    File "C:\Users\adminUser\AppData\Local\Temp\pip-build-env-n9c8za34\overlay\Lib\site-packages\xsdata\codegen\writer.py", line 53, in from_config
      raise CodeGenerationError(
  xsdata.exceptions.CodeGenerationError: Unknown output format: 'pydata'
  error: [Errno 2] No such file or directory: 'ismrmrdschema/__init__.py'
  ----------------------------------------
  ERROR: Failed building wheel for ismrmrd
Failed to build ismrmrd
ERROR: Could not build wheels for ismrmrd which use PEP 517 and cannot be installed directly
```

**Comment by LeeHL451** [comment]
Hi,

I am getting exactly the same error on Ubuntu 20.04 + miniconda python 3.8.10
Any suggestion will be appreciated!

**Comment by Pedro-Filipe** [comment]
I tried `pip install ismrmrd` instead and I didn't get an error, but I am not 100% sure this is the correct thing to do. Can anyone with more knowledge comment on this?

**Comment by hansenms** [comment]
The recommend approach to installing is to just use pip, there is no reason to build:

```
pip3 install ismrmrd==1.9.8
```
